core/src/main/scala/com/github/gvolpe/fs2redis/algebra/basic.scala, core/src/main/scala/com/github/gvolpe/fs2redis/algebra/streams.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/pubsub/Fs2PubSubCommands.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2RedisBasicDemo.scala
- Implementation for all the basic string commands. 
- `Incr` and `Decr` commands are validated at compile time but they can still fail if a key is set externally.
=> Implementation for all the basic string commands

core/src/main/scala/com/github/gvolpe/fs2redis/algebra/hash.scala, core/src/main/scala/com/github/gvolpe/fs2redis/algebra/string.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2RedisHashDemo.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2RedisStringsDemo.scala
The only missing command is `HSCAN` which I intentionally decided not to implement because I'm still not sure about what's the best design. Maybe it'd be better at the Stream level.
=> Hash commands API

README.md, core/src/main/scala/com/github/gvolpe/fs2redis/algebra/sortedsets.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala
=> Sorted Sets API

core/src/main/scala/com/github/gvolpe/fs2redis/algebra/sortedsets.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala, core/src/main/scala/com/github/gvolpe/fs2redis/model.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Demo.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2RedisGeoDemo.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2RedisListsDemo.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2RedisSortedSetsDemo.scala
=> SortedSets, Lists and Geo APIs examples

README.md, site/src/main/resources/microsite/data/menu.yml, site/src/main/tut/effects/geo.md, site/src/main/tut/effects/hashes.md, site/src/main/tut/effects/index.md, site/src/main/tut/effects/lists.md, site/src/main/tut/effects/sets.md, site/src/main/tut/effects/sortedsets.md, site/src/main/tut/effects/strings.md, site/src/main/tut/streams/index.md, site/src/main/tut/streams/pubsub.md, site/src/main/tut/streams/streams.md
- Added menu for stream-based and effect-based APIs. 
- Added docs for all the supported command APIs.
=> Documentation for the microsite

core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/connection/Fs2RedisClient.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/connection/Fs2RedisMasterSlave.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/streams/Fs2Streaming.scala, core/src/main/scala/com/github/gvolpe/fs2redis/model.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2RedisMasterSlaveStringsDemo.scala, site/src/main/tut/effects/index.md, site/src/main/tut/streams/streams.md
cc:/ @calvinlfer coming soon :)
=> Master / Slave connection support

build.sbt, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/connection/Fs2RedisClient.scala, core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/connection/Fs2RedisMasterSlave.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2PubSubDemo.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2PublisherDemo.scala, examples/src/main/scala/com/github/gvolpe/fs2redis/Fs2StreamingDemo.scala, project/Dependencies.scala, site/src/main/tut/effects/geo.md, site/src/main/tut/effects/hashes.md, site/src/main/tut/effects/index.md, site/src/main/tut/effects/lists.md, site/src/main/tut/effects/sets.md, site/src/main/tut/effects/sortedsets.md, site/src/main/tut/effects/strings.md, site/src/main/tut/streams/pubsub.md, site/src/main/tut/streams/streams.md
Preparing for upcoming final releases. Upgrading to latest `cats-effect 1.0.0-RC3` and `fs2 1.0.0-M4`.
=> Upgrade to cats-effect 1.0.0-RC3 and fs2 1.0.0-M4

.travis.yml, build.sbt, core/src/main/scala/com/github/gvolpe/fs2redis/connection/Fs2RedisClient.scala, core/src/main/scala/com/github/gvolpe/fs2redis/connection/Fs2RedisMasterSlave.scala, core/src/main/scala/com/github/gvolpe/fs2redis/util/JRFuture.scala, effects/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala, project/Dependencies.scala, test-support/src/main/scala/com/github/gvolpe/fs2redis/DockerRedis.scala, tests/src/test/scala/com/github/gvolpe/fs2redis/Fs2RedisSpec.scala
=> Test support module that spins up a Redis instance using Docker

build.sbt
=> Aggregating log4cats module

modules/effects/src/main/scala/com/github/gvolpe/fs2redis/algebra/sortedsets.scala, modules/effects/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala
=> Range value types are not associated with V when querying by score

modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClusterClient.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisConnection.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/domain.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/PubSubDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/PublisherDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisClusterStringsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisClusterTransactionsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisGeoDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisHashesDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisListsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisMasterSlaveStringsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisSetsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisSortedSetsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisStringsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisTransactionsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/StreamingDemo.scala, version.sbt
closes #93 
Here's a first sketch @ikempf . See `RedisClusterTransactionsDemo` and let me know if that could work for you. Still missing tests and documentation but that can be added in another PR.
=> Adding support for single-shard transactions

modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/server.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/Fs2TestScenarios.scala, version.sbt
Commands: INFO, DBSIZE, LASTSAVE, SLOWLOG length
=> Added server commands

modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/strings.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/effects.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/Fs2TestScenarios.scala
added support of options for `set` command - https://redis.io/commands/set#options
=> args support for `set` command

modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/keys.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/Fs2TestScenarios.scala
=> Support for TTL and PTTL commands

build.sbt, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/Subscriber.scala, project/Dependencies.scala
closes #193 
Also ran formatter...
=> Upgrading cats to 2.1.0

build.sbt, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClient.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClusterClient.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisConnection.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisMasterReplica.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisURI.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/effect/JRFuture.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/pipeline.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/transactions.scala, modules/log4cats/src/main/scala/dev/profunktor/redis4cats/log4cats.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/LivePubSubCommands.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/LivePubSubStats.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/PubSub.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/Publisher.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/Subscriber.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/internals/PubSubInternals.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/streams/Fs2RawStreaming.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/streams/Fs2Streaming.scala, modules/test-support/src/main/scala/dev/profunktor/redis4cats/testLogger.scala, project/Dependencies.scala
=> Trying out Context Applied compiler plugin

modules/core/src/test/scala/dev/profunktor/redis4cats/effect/JRFutureSpec.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisSpec.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
Just to give #233 a little bit of reassurance...
=> Adding test for canceled transactions

modules/core/src/main/scala/dev/profunktor/redis4cats/domain.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/keys.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala
=> Scan command impl

modules/effects/src/main/scala/dev/profunktor/redis4cats/pipeline.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/runner.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/transactions.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisPipelineDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisTransactionsDemo.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisClusterSpec.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisSpec.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala, site/docs/pipelining.md
Also, I generalized both transactions and pipelining into a single `Runner`, since both are pretty similar.
=> Pipelining using HLists

modules/core/src/test/scala/dev/profunktor/redis4cats/effect/JRFutureSpec.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/LoggerIOApp.scala, project/Dependencies.scala, version.sbt
=> Polishing release v0.10.0-RC1

build.sbt, modules/core/src/test/scala/dev/profunktor/redis4cats/HListSpec.scala, modules/core/src/test/scala/dev/profunktor/redis4cats/codecs/DisciplineSuite.scala, modules/core/src/test/scala/dev/profunktor/redis4cats/codecs/SplitMorphismTest.scala, modules/core/src/test/scala/dev/profunktor/redis4cats/effect/JRFutureSpec.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/Redis4CatsFunSuite.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisClusterSpec.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala, project/Dependencies.scala
=> Migrating over to Munit

build.sbt, modules/core/src/main/scala/dev/profunktor/redis4cats/codecs/Codecs.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/JsonCodecDemo.scala, project/Dependencies.scala, site/docs/codecs.md, site/src/main/resources/microsite/data/menu.yml
It includes a JsonCodec example
=> Codecs documentation

modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClient.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisMasterReplica.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala, site/docs/effects/index.md
Provides a way to configure the underlying Redis Client via `io.lettuce.core.ClientOptions`.
=> [Feature] - Client options

.github/workflows/release.yml, build.sbt, modules/tests/src/test/scala/dev/profunktor/redis4cats/Redis4CatsFunSuite.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisSpec.scala, project/plugins.sbt, version.sbt
Setting up https://github.com/olafurpg/sbt-ci-release
=> Automating releases from the CI build

modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2Streaming.scala
Exposing a `Resource` is more flexible than a `Stream`. I named them differently to avoid a breaking change but let me know if you have any preference.
=> Add Streaming constructors that return a Resource

modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/keys.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/effects.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
=> Support for PEXPIRE, EXPIREAT & PEXPIREAT

modules/core/src/main/scala/dev/profunktor/redis4cats/effect/JRFuture.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/commands.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
Trying to fix #344 or at least identify the root cause.
I added some logs on `futureLift` after doing some investigation. Found two relevant articles:
- https://stackoverflow.com/questions/17265022/what-is-a-boxed-error-in-scala
- https://engineering.footballradar.com/scala-snacks-part-2-dont-assert-your-requirement/
We were using `assert` from Scala in `TestScenarios` instead of the one defined by the testing framework, that might be one of the reasons.
=> Attempt to fix the Boxed Error seen on the CI build

modules/examples/src/main/scala/dev/profunktor/redis4cats/PubSubDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/PublisherDemo.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/pubsub/PubSub.scala, site/docs/client.md, site/docs/streams/pubsub.md
Closes #330, but I'm not sure about saving backward compatibility
=> PubSub.mkConnection using resource

modules/core/src/main/scala/dev/profunktor/redis4cats/config.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClusterClient.scala
Partially addresses https://github.com/profunktor/redis4cats/issues/383
Quick & dirty POC on what high-level support for cluster topology view refresh could look like. 
This is missing support for individual triggers in the adaptive strategy, as well as a programmatic refresh API, both of which might not be particularly useful.
A separate API for setting the client options could also be created, which would in turn set the options using the `underlying` Java client.
=> Support refresh of the redis cluster topology view

modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/sets.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/sortedsets.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
Updated the signature of some commands for Set and SortedSet manipulations so that they keep the results returned from the Redis.
Closes #396
=> Keep the results of set update commands

modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisSpec.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala, project/Dependencies.scala
=> Update cats-core to 2.3.0 + mark pipelining test as flaky

modules/core/src/main/scala/dev/profunktor/redis4cats/hlist.scala, modules/core/src/test/scala/dev/profunktor/redis4cats/HListSpec.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/pipeline.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/runner.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/transactions.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala, site/docs/transactions.md
A deterministic Xmas gift! :santa:
=> Transactions: replacing internal delay with synchronizer

modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2Streaming.scala
Bug fix. From https://redis.io/commands/xread :
```
So we start with a list of keys, and later continue with all the associated IDs, representing the last ID we received for that stream, so that the call will serve us only greater IDs from the same stream.
```
Currently `RedisStream` is skipping elements like 123456-1
=> XREAD id should be the last consumed one (no increment)

modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisClusterFromUnderlyingDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisClusterStringsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisClusterTransactionsDemo.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/Redis4CatsFunSuite.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisStreamSpec.scala, site/docs/client.md
Similar to `RedisMasterReplica`.
=> Pass Lettuce ReadFrom option to cluster connection

modules/examples/src/main/scala/dev/profunktor/redis4cats/LoggerIOApp.scala, modules/log4cats/src/main/scala/dev/profunktor/redis4cats/log4cats.scala, project/Dependencies.scala, site/docs/client.md, site/docs/effects/connection.md, site/docs/effects/geo.md, site/docs/effects/hashes.md, site/docs/effects/keys.md, site/docs/effects/lists.md, site/docs/effects/scripting.md, site/docs/effects/server.md, site/docs/effects/sets.md, site/docs/effects/sortedsets.md, site/docs/effects/strings.md, site/docs/pipelining.md, site/docs/streams/pubsub.md, site/docs/streams/streams.md, site/docs/transactions.md
closes #476 
closes #475 
closes #470 
closes #467
=> Update some dependencies

build.sbt, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClient.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/hlist.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala, modules/effects/src/main/scala/dev/profunktor/redis4cats/runner.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/ConcurrentTransactionsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisClusterTransactionsDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisPipelineDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisTransactionsDemo.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala, project/Dependencies.scala, project/plugins.sbt
=> Fix - remove custom versions

modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2RawStreaming.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2Streaming.scala, modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/streams.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisStreamSpec.scala
Cherry-picking and adapting the work done in #539
Closes #460 
Closes #445 (maybe)
=> Fix streaming read (cherry-pick #539)

modules/core/src/main/scala/dev/profunktor/redis4cats/effect/MkRedis.scala
Credit for discovering goes to @vorner
=> MkRedis: Fix typo in implicitNotFound

modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisPipelineDemo.scala, modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisTransactionsDemo.scala, project/Dependencies.scala
=> fix updates of cats-effect & fs2

.github/workflows/ci.yml, modules/core/src/main/scala/dev/profunktor/redis4cats/config.scala, modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClusterClient.scala, modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisStreamSpec.scala
Porting https://github.com/profunktor/redis4cats/pull/556 into master branch to have the change in 0.x.x release
=> Make topologyViewRefreshStrategy configurable
