- core/src/main/scala/com/github/gvolpe/fs2redis/algebra/strings.scala
- core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala
**Change:**
The Redis `DEL` command can take arbitrary many keys to delete at once and Lettuce models this via a vararg method which is currently not exposed by fs2-redis, it only allows deletion of a single key. This PR introduces the vararg to fs2-redis, replacing the old method. This is source-compatible, but AFAIK not binary-compatible - given the early stage of this project I assume this is fine. Alternatively, one could overload the `del(…)` method.
**Use case:**
Any place where more than one delete is present, they can be merged. For example, we have regular updates on a data set which is split to several keys. After updating, we want to delete all the keys which didn't get updated as they contain outdated information.
> Allow deletion of several keys via vararg on StringCommands.del()

- core/src/main/scala/com/github/gvolpe/fs2redis/algebra/strings.scala
- core/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala
mGet should not throw an exception when getting the value from a key which has no value set.
> Implement safe mGet

- build.sbt
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
By manually adding the `Tut plugin 0.6.7` overriding the one used by `sbt-microsites`. It as fixed here: https://github.com/tpolecat/tut/issues/231
Definitely closes https://github.com/outr/scribe/issues/80
> Fixing integration between scribe and tut for Scala 2.12.6

- effects/src/main/scala/com/github/gvolpe/fs2redis/algebra/hashes.scala
- effects/src/main/scala/com/github/gvolpe/fs2redis/algebra/strings.scala
- effects/src/main/scala/com/github/gvolpe/fs2redis/interpreter/Fs2Redis.scala
- tests/src/test/scala/com/github/gvolpe/fs2redis/Fs2RedisClusterSpec.scala
- tests/src/test/scala/com/github/gvolpe/fs2redis/Fs2TestScenarios.scala
closes #58 
Changed signature of `*setNx` methods so they return `F[Boolean]` instead of `F[Unit]`.
> Changed *setNx API signatures

- modules/core/src/main/scala/dev/profunktor/redis4cats/effect/JRFuture.scala
- modules/core/src/test/scala/dev/profunktor/redis4cats/effect/JRFutureSpec.scala
- Use guarantee to ensure the computation shifts the thread pool even o…n failure conditions
- Write a test to verify this behavior
- `EmptyValue` cleanup
Addresses https://github.com/profunktor/redis4cats/pull/122
> Better thread shifting semantics on failure conditions

- build.sbt
- modules/core/src/test/scala-2.12/dev/profunktor/redis4cats/testutils/Redis4CatsAsyncFunSuite.scala
- modules/test-support/src/main/scala-2.12/dev/profunktor/redis4cats/testutils/Redis4CatsAsyncFunSuite.scala
- modules/test-support/src/main/scala-2.12/dev/profunktor/redis4cats/testutils/Redis4CatsFunSuite.scala
- project/Dependencies.scala
Closes #110 and #130 
There's still some more polishing to do but I'll leave that to future PRs before releasing a new version. i.e. there's no longer need to discriminate between Scala versions in Test Suites.
Also, I had to set `JAVA_OPTS="-XX:MaxMetaspaceSize=1024M"` to run the tests as I was getting OOM error as reported [here](https://github.com/sbt/sbt/issues/4686).
> Unifying dependencies for the different Scala versions

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/strings.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/Fs2TestScenarios.scala
closes #151 
>We can split all key-related commands (`del`, `expire`, `exists`, etc.) to separate trait.
> Add exists command support

- modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisMasterReplica.scala
- modules/core/src/main/scala/dev/profunktor/redis4cats/domain.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisMasterReplicaStringsDemo.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/streams/Fs2Streaming.scala
- project/Dependencies.scala
- site/src/main/tut/effects/index.md
- site/src/main/tut/streams/streams.md
closes #145 
Renamed all `MasterSlave` stuff to `MasterReplica` as in Lettuce. 
We'll need to cut a new major version soon given that these are breaking changes.
> Upgrading to lettuce-5.2.0.RELEASE

- modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisURI.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/effects.scala
As suggested by @tpolecat, using `catchNonFatal` instead of `delay`.
> Relaxing constraint on RedisURI.make

- modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisConnection.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/redis.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala
This is required to be able to change the `F` of `RedisCommands` as the internal connection is not visible from outside (not held in a val of the class)
> Add liftK to RedisCommands

- README.md
- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/redis.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/scripts.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/effects.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisScriptsDemo.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisClusterSpec.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisSpec.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
- site/docs/effects/index.md
- site/docs/effects/scripting.md
- site/src/main/resources/microsite/data/menu.yml
Includes a separate Algebra for scripting-related commands and their implementation and BaseRedis. Plus tests, demo and docs.
Use case: A lot of interesting applications with Redis rely on some atomicity you can't get by just sending simple commands over wire, so you have to rely on Lua scripting, for example for locking algorithms: https://redis.io/topics/distlock
Most of the implementation is straight-forward wrapping of Lettuce, I'll comment below on one or two unusual things. Feedback and ideas for improvements on these especially welcome!
> Add support for scripting

- modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/transactions.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/LoggerIOApp.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/PubSubDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/PublisherDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisTransactionsDemo.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/LivePubSubCommands.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/interpreter/pubsub/Publisher.scala
- site/docs/transactions.md
Transactions were working but any computation running after a transaction was never executed due to the core of the transactions hanging while trying to join spawned fibers (which happen to be Lettuce commands that never return).
This fix removes the joins and always cancels all the spawned fibers, which in case of a completed computation it'll be a no-op.
Still, if you can avoid using transactions, prefer not to use this.
/cc @sloshy
> Fixing hanging transactions

- modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala
These commands take their timeout in seconds (see Lettuce Javadoc or https://redis.io/commands/blpop#blocking-behavior), but the `Redis` interpreter converted the given `FiniteDuration` into milliseconds.
PS: Given the fact that a `0` timeout means infinite blocking according to the Redis docs, I wonder whether it would make sense to take an `Option[FiniteDuration]` (`None` = no timeout = `0` sent to Redis) or just a `Duration` (and map `Duration.Inf` to `0`). Any opinions?
> Fix timeout unit for blPop, brPop & brPopLPush

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/lists.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/interpreter/Redis.scala
`blPop`, `brPop` & `brPopLPush` now take a `Duration` instead of a `FiniteDuration` to allow specifying an infinite timeout in a more typed fashion. See discussion on #235
> Let blocking commands take Duration instead of FiniteDuration

- README.md
Adds a link to the micro site and badges for all modules on javadoc.io (they automatically point to the latest version, no update needed).
Closes #251
> Add documentation section to Readme

- modules/core/src/main/scala/dev/profunktor/redis4cats/hlist.scala
- modules/core/src/test/scala/dev/profunktor/redis4cats/HListSpec.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/pipeline.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/transactions.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisPipelineDemo.scala
- site/docs/pipelining.md
- site/docs/transactions.md
Having the possibility to discard `Unit` types from an `HList` is quite useful for transactions and pipelining, since normally one wouldn't care about the result of a `SET`.
This PR adds a new function `exec_` for transactions and pipelining, which actually filters out values of type `Unit`, giving us the power to do this:
```scala
val operations =
cmd.set(key1, "noop") :: cmd.set(key2, "windows") :: cmd.get(key1) ::
cmd.set(key1, "nix") :: cmd.set(key2, "linux") :: cmd.get(key1) :: HNil
val prog =
RedisPipeline(cmd)
.exec_(operations)
.flatMap {
case res1 ~: res2 ~: HNil =>
putStrLn(s"res1: $res1, res2: $res2")
}
```
Whereas using `exec` would preserve the values of type `Unit`:
```scala
val operations =
cmd.set(key1, "noop") :: cmd.set(key2, "windows") :: cmd.get(key1) ::
cmd.set(key1, …
```
> Filter Unit types from HList

- modules/effects/src/main/scala/dev/profunktor/redis4cats/pipeline.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/runner.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/transactions.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisPipelineDemo.scala
- site/docs/pipelining.md
- site/docs/transactions.md
I figured `filterExec` is a better name for "execute" and "filter out" values than `exec_`, which following conventions (such as `traverse_` and `sequence_`) would mean discard its value instead of filtering some values out.
> Renaming exec_ with filterExec

- README.md
- modules/core/src/main/scala/dev/profunktor/redis4cats/effect/Log.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/Redis4CatsFunSuite.scala
- site/docs/quickstart.md
Internal logging is mainly used to log the status of connections so we don't need a `noop` instance for every `Applicative[F]`, one for `IO` is enough and slightly reduces the import syntax.
> Renaming noop logging

- README.md
- modules/core/src/main/scala/dev/profunktor/redis4cats/effect/Log.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/Redis4CatsFunSuite.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
- site/docs/effects/index.md
- site/docs/quickstart.md
- Moving back to the `NoOp` instance for any `Applicative`, since I forgot people might use other effect types.
- Adding more documentation around logging.
- Introducing a `Log.Stdout` instance for any `Sync`.
> Stdout logging + docs

- modules/core/src/main/scala/dev/profunktor/redis4cats/codecs/Codecs.scala
- modules/core/src/main/scala/dev/profunktor/redis4cats/data.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/Demo.scala
- site/docs/codecs.md
- Adding `deflate`, `gzip` and `secure` (for encrypted keys) codec constructors. 
- Adding examples of custom key codecs as documentation, closes #196 .
- Reworking codecs implementation (removing unnecessary `ToByteBufEncoder`).
> Codecs: compression, encryption & docs

- modules/effects/src/main/scala/dev/profunktor/redis4cats/commands.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisLiftKDemo.scala
The `liftK` function is now an extension method to `RedisCommands[F, K, V]`.
> Removing liftK from the commands algebra

- modules/examples/src/main/scala/dev/profunktor/redis4cats/ConcurrentTransactionsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/JsonCodecDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/LoggerIOApp.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/PubSubDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/PublisherDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisClusterStringsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisClusterTransactionsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisGeoDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisHashesDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisKeysDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisLiftKDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisListsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisMasterReplicaStringsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisPipelineDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisScriptsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisSetsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisSortedSetsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisStringsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/RedisTransactionsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/StreamingDemo.scala
- site/docs/transactions.md
It includes documentation for optimistic locking using the WATCH command (closes #73).
> Examples: Concurrent transactions with optimistic locking

- modules/core/src/main/scala/dev/profunktor/redis4cats/config.scala
- modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClient.scala
- modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClusterClient.scala
- modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisMasterReplica.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisSpec.scala
- site/docs/client.md
Shutdown parameters aren't covered by the existing configuration options, but due to unfortunate defaults in Lettuce 5.3 (fixed in 6.0), shutting down a client will always wait for 2s. This PR allows configuring this via a new `Redis4CatsConfig` and plugs in the better defaults from Lettuce 6.0.
Speeds up test execution a lot, from 50-60s down to 5-10s on my local machine.
> Add Redis4CatsConfig with ability to control shutdown timeouts

- modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2RawStreaming.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/streams.scala
Hello,
there is an optional `MAXLEN` param for `XADD` command. I think this is actually what you usually want for production use. Neither `RawStreaming` nor `Streaming` currently supports it.
This pull request is just an illustration how it could look like for `RawStreaming`. I'm happy to adjust it to desired conventions and to work on `Streaming` api.
1. I propose not to support exact length trim (without `~`). Cannot image usage for that. OK?
2. Which one of these or something else?
- additional `xadd` method param (got my vote and is included in PR),
- use `io.lettuce.core.XAddArgs` class,
- make more *scalish* XAddArgs.
Currently `StreamingMessage` is used both for input and output. I'd add new class `XAddStreamingMessage` but maybe there's smarter way to do it.
> Support for XADD MAXLEN ~ maxlen param

- modules/core/src/main/scala/dev/profunktor/redis4cats/connection/RedisClient.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/ConcurrentTransactionsDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/PubSubDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/PublisherDemo.scala
- modules/examples/src/main/scala/dev/profunktor/redis4cats/StreamingDemo.scala
- site/docs/client.md
- site/docs/streams/pubsub.md
- site/docs/streams/streams.md
- site/docs/transactions.md
Instead of 
```scala
for {
uri <- Resource.liftF(RedisURI.make[IO]("redis://localhost"))
cli <- RedisClient[IO](uri)
} yield cli
```
We can now leave the creation of the URI to the client constructor
```scala
RedisClient[IO].from("redis://localhost")
```
There are other ways to create a client as well:
- `RedisClient[IO].withOptions(uri, opts)`
- `RedisClient[IO].custom(uri, opts, config)`
> Simplify creation of RedisClient

- modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2Streaming.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/streams.scala
- site/docs/streams/streams.md
It's useful to catch the `MessageId` we get after appending, so that we can use it as an offset when reading.
> Return MessageId in Streaming#append

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/keys.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/effects.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisSpec.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
Closes #331
In the end I decided to keep `cursor` separated. It closely resembles lettuce API but the implementation does not look too DRY.
> Implement SCAN with arguments

- modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2Streaming.scala
From the [docs](https://redis.io/topics/streams-intro):
The entry ID returned by the XADD command, and identifying univocally each entry inside a given stream, is composed of two parts:
```
<millisecondsTime>-<sequenceNumber>
```
Using `dropRight(2)` is unsafe and fails under load (found this during load testing 😅 ).
> Properly split entry IDs in Streaming

- modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2Streaming.scala
[Docs](https://redis.io/topics/streams-intro):
> In order to continue the iteration with the next two items, I have to pick the last ID returned, that is 1519073279157-0 and add 1 to the sequence number part of the ID. Note that the sequence number is 64 bit so there is no need to check for overflows. The resulting ID, that is 1519073279157-1 in this case, can now be used as the new start argument for the next XRANGE call
Incrementing the timestamp will lose the other entries with the same timestamp.
> Increment sequence number instead of timestamp to get the next offset

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/lists.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
- return `F[Option[(K, V)]]` instead of `F[(K, V)]`
- accept a non-empty list of keys
> fix `blpop` and `brpop`

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/sortedsets.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
- site/docs/effects/index.md
Implemented the following commands for sorted sets:
- [ZPOPMIN](https://redis.io/commands/zpopmin)
- [ZPOPMAX](https://redis.io/commands/zpopmax)
- [BZPOPMIN](https://redis.io/commands/bzpopmin)
- [BZPOPMAX](https://redis.io/commands/bzpopmax)
> sorted sets: zpopmin, zpopmax, bzpopmin, bzpopmax

- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
> Fix: hmGet throws an exception if one of the keys doesn't have a value

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/sortedsets.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
The current ZCOUNT signatures forces the `ZRange` to have the type of `V` but the [docs](https://redis.io/commands/zcount) say you need to pass a score, which is independent from the value type `V`. As per the docs, the semantics should be the same as `ZRANGEBYSCORE` which has signature `zRangeByScore[T: Numeric](key: K, range: ZRange[T], ...)`.
> Fix ZCOUNT signature

- build.sbt
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
The [documentation](https://redis.io/commands/ttl) says the response is
> Integer reply: TTL in seconds, or a negative value in order to signal an error (see the description above).
I don't know why we were only checking `-2` and `-1`.
> Improve ttl implementations

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/connection.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
Closes https://github.com/profunktor/redis4cats/issues/246
> Add auth command

- modules/streams/src/main/scala/dev/profunktor/redis4cats/streams/Fs2RawStreaming.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/Redis4CatsFunSuite.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisStreamSpec.scala
This is about: https://github.com/profunktor/redis4cats/issues/446
> Asynchronous XREAD to prevent constant polling of redis streams

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/sortedsets.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
Hi! I've found that range parameter in zRemRangeByScore depends on stored value type and must be numeric. But it must be numeric no matter what type of stored value is.
So I've fixed that
> Improving zRemRangeByScore method interface

- modules/log4cats/src/main/scala/dev/profunktor/redis4cats/log4cats.scala
There is an issue introduced via #485. The wrong summoner causes recursion.
> Fix log4cats adapter

- modules/streams/src/main/scala/dev/profunktor/redis4cats/pubsub/internals/LivePubSubCommands.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/pubsub/internals/PubSubInternals.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/pubsub/internals/Subscriber.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/pubsub/internals/package.scala
Topic should be a resource with the underlying Dispatcher's lifetime coupled to the lifetime of the stream
> Couple Dispatcher lifetime to stream

- modules/examples/src/main/scala/dev/profunktor/redis4cats/PubSubDemo.scala
- modules/streams/src/main/scala/dev/profunktor/redis4cats/pubsub/internals/PubSubInternals.scala
> Fix issue with listener not being removed when subscription is released

- modules/effects/src/main/scala/dev/profunktor/redis4cats/algebra/hashes.scala
- modules/effects/src/main/scala/dev/profunktor/redis4cats/redis.scala
- modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
As per Redis docs (https://redis.io/commands/HMSET):
> As per Redis 4.0.0, HMSET is considered deprecated.
> Please prefer HSET in new code.
Fixes https://github.com/profunktor/redis4cats/issues/639.
> Add variadic hSet and deprecate hmSet
